In [132]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [133]:
pd_data = pd.read_csv('전국도서관표준데이터.csv', encoding='cp949')

# print(pd_data.head())

for i,n in enumerate(pd_data.columns):
    print(i, n)

0 도서관명
1 시도명
2 시군구명
3 도서관유형
4 휴관일
5 평일운영시작시각
6 평일운영종료시각
7 토요일운영시작시각
8 토요일운영종료시각
9 공휴일운영시작시각
10 공휴일운영종료시각
11 열람좌석수
12 자료수(도서)
13 자료수(연속간행물)
14 자료수(비도서)
15 대출가능권수
16 대출가능일수
17 소재지도로명주소
18 운영기관명
19 도서관전화번호
20 부지면적
21 건물면적
22 홈페이지주소
23 위도
24 경도
25 데이터기준일자
26 제공기관코드
27 제공기관명

In [134]:
sub_df = pd_data[['시도명', '도서관유형', '자료수(도서)']]

print(sub_df)

        시도명  도서관유형  자료수(도서)
0       경기도  작은도서관     5025
1       경기도  작은도서관    13261
2       경기도  작은도서관    26320
3       경기도  작은도서관    27984
4       경기도  작은도서관     8903
...     ...    ...      ...
3451    경기도  공공도서관    97137
3452    경기도  공공도서관    97097
3453    경기도  공공도서관   231651
3454  부산광역시  작은도서관     9573
3455  부산광역시  작은도서관     1905

[3456 rows x 3 columns]

In [135]:
g1 = sub_df.groupby(['시도명', '도서관유형'])
df1 = g1.count()
df1.index = df1.index.swaplevel(0,1)
df1

                자료수(도서)
도서관유형  시도명
공공도서관  강원도           47
작은도서관  강원도           32
공공도서관  경기도          283
어린이도서관 경기도           11
작은도서관  경기도          199
전문도서관  경기도            2
공공도서관  경상남도         123
작은도서관  경상남도         303
공공도서관  경상북도         108
어린이도서관 경상북도           1
작은도서관  경상북도          59
공공도서관  광주광역시         49
작은도서관  광주광역시        298
전문도서관  광주광역시          1
공공도서관  대구광역시         41
작은도서관  대구광역시        187
전문도서관  대구광역시          1
공공도서관  대전광역시         48
작은도서관  대전광역시         62
공공도서관  부산광역시         35
어린이도서관 부산광역시          2
작은도서관  부산광역시        148
공공도서관  서울특별시        189
어린이도서관 서울특별시          4
작은도서관  서울특별시        348
학교도서관  서울특별시          2
공공도서관  세종특별자치시       14
작은도서관  세종특별자치시        6
공공도서관  울산광역시         22
작은도서관  울산광역시        123
전문도서관  울산광역시          1
공공도서관  인천광역시         56
어린이도서관 인천광역시         10
작은도서관  인천광역시        128
공공도서관  전라남도          67
어린이도서관 전라남도           2
작은도서관  전라남도          59
공공도서관  전라북도          61
어린이도서관 전라북도           1
작은도서관  전라북도          96
공공도서관  제주특별자치도       22
작은도서관  제주특별자치도       14
장애인도서관 제주특별자치도        1
공공도서관  충청남도          43
작은도서관  충청남도          34
공공도서관  충청북도          75
대학도서관  충청북도           1
어린이도서관 충청북도           2
작은도서관  충청북도          11
학교도서관  충청북도          24

In [136]:
df2 = g1.agg([np.sum, np.max])
# df2.columns = df2.columns.swaplevel(0,1)
df2

                 자료수(도서)
                     sum    amax
시도명     도서관유형
강원도     공공도서관    2847914  354607
        작은도서관     263046   21482
경기도     공공도서관   32111062  722502
        어린이도서관   1046594  134499
        작은도서관    2336253   46594
        전문도서관      24865   14932
경상남도    공공도서관   11628077  367123
        작은도서관    2526976  172783
경상북도    공공도서관    6811687  298801
        어린이도서관     52076   52076
        작은도서관     435117   22341
광주광역시   공공도서관    4222860  363769
        작은도서관    1353254   26747
        전문도서관      58340   58340
대구광역시   공공도서관    5283846  520745
        작은도서관    1442401   96531
        전문도서관     100000  100000
대전광역시   공공도서관    5205552  872312
        작은도서관     342476   19133
부산광역시   공공도서관    3097306  249939
        어린이도서관     61173   49894
        작은도서관     948617   46525
서울특별시   공공도서관    9766412  301007
        어린이도서관     95900   30899
        작은도서관    3134912   30132
        학교도서관      54702   28525
세종특별자치시 공공도서관     644877  117018
        작은도서관      49828   15158
울산광역시   공공도서관    2838209  309454
        작은도서관     785272   31392
        전문도서관      11653   11653
인천광역시   공공도서관    5152771  547309
        어린이도서관    309056   72896
        작은도서관     803099   37537
전라남도    공공도서관    6458255  322911
        어린이도서관    118406   66059
        작은도서관     239427   11529
전라북도    공공도서관    4731982  244835
        어린이도서관     28055   28055
        작은도서관     912160   35100
제주특별자치도 공공도서관    2693342  318076
        작은도서관      91242   15046
        장애인도서관      3196    3196
충청남도    공공도서관    4232171  312936
        작은도서관     270719   19300
충청북도    공공도서관    7378160  629434
        대학도서관     170997  170997
        어린이도서관    230661  121538
        작은도서관      45477   21217
        학교도서관     268625   18446

In [137]:
df2 = df2.stack()
df2

                   자료수(도서)
시도명  도서관유형
강원도  공공도서관  sum    2847914
            amax    354607
     작은도서관  sum     263046
            amax     21482
경기도  공공도서관  sum   32111062
...                    ...
충청북도 어린이도서관 amax    121538
     작은도서관  sum      45477
            amax     21217
     학교도서관  sum     268625
            amax     18446

[100 rows x 1 columns]

In [138]:
df3 = df2.unstack()
df3

                 자료수(도서)
                     sum    amax
시도명     도서관유형
강원도     공공도서관    2847914  354607
        작은도서관     263046   21482
경기도     공공도서관   32111062  722502
        어린이도서관   1046594  134499
        작은도서관    2336253   46594
        전문도서관      24865   14932
경상남도    공공도서관   11628077  367123
        작은도서관    2526976  172783
경상북도    공공도서관    6811687  298801
        어린이도서관     52076   52076
        작은도서관     435117   22341
광주광역시   공공도서관    4222860  363769
        작은도서관    1353254   26747
        전문도서관      58340   58340
대구광역시   공공도서관    5283846  520745
        작은도서관    1442401   96531
        전문도서관     100000  100000
대전광역시   공공도서관    5205552  872312
        작은도서관     342476   19133
부산광역시   공공도서관    3097306  249939
        어린이도서관     61173   49894
        작은도서관     948617   46525
서울특별시   공공도서관    9766412  301007
        어린이도서관     95900   30899
        작은도서관    3134912   30132
        학교도서관      54702   28525
세종특별자치시 공공도서관     644877  117018
        작은도서관      49828   15158
울산광역시   공공도서관    2838209  309454
        작은도서관     785272   31392
        전문도서관      11653   11653
인천광역시   공공도서관    5152771  547309
        어린이도서관    309056   72896
        작은도서관     803099   37537
전라남도    공공도서관    6458255  322911
        어린이도서관    118406   66059
        작은도서관     239427   11529
전라북도    공공도서관    4731982  244835
        어린이도서관     28055   28055
        작은도서관     912160   35100
제주특별자치도 공공도서관    2693342  318076
        작은도서관      91242   15046
        장애인도서관      3196    3196
충청남도    공공도서관    4232171  312936
        작은도서관     270719   19300
충청북도    공공도서관    7378160  629434
        대학도서관     170997  170997
        어린이도서관    230661  121538
        작은도서관      45477   21217
        학교도서관     268625   18446

In [139]:
df4 = df3.unstack()
df4

            자료수(도서)                                                    \
                sum
도서관유형         공공도서관     대학도서관     어린이도서관      작은도서관  장애인도서관     전문도서관
시도명
강원도       2847914.0       NaN        NaN   263046.0     NaN       NaN
경기도      32111062.0       NaN  1046594.0  2336253.0     NaN   24865.0
경상남도     11628077.0       NaN        NaN  2526976.0     NaN       NaN
경상북도      6811687.0       NaN    52076.0   435117.0     NaN       NaN
광주광역시     4222860.0       NaN        NaN  1353254.0     NaN   58340.0
대구광역시     5283846.0       NaN        NaN  1442401.0     NaN  100000.0
대전광역시     5205552.0       NaN        NaN   342476.0     NaN       NaN
부산광역시     3097306.0       NaN    61173.0   948617.0     NaN       NaN
서울특별시     9766412.0       NaN    95900.0  3134912.0     NaN       NaN
세종특별자치시    644877.0       NaN        NaN    49828.0     NaN       NaN
울산광역시     2838209.0       NaN        NaN   785272.0     NaN   11653.0
인천광역시     5152771.0       NaN   309056.0   803099.0     NaN       NaN
전라남도      6458255.0       NaN   118406.0   239427.0     NaN       NaN
전라북도      4731982.0       NaN    28055.0   912160.0     NaN       NaN
제주특별자치도   2693342.0       NaN        NaN    91242.0  3196.0       NaN
충청남도      4232171.0       NaN        NaN   270719.0     NaN       NaN
충청북도      7378160.0  170997.0   230661.0    45477.0     NaN       NaN

                                                                             \
                       amax
도서관유형       학교도서관     공공도서관     대학도서관    어린이도서관     작은도서관  장애인도서관     전문도서관
시도명
강원도           NaN  354607.0       NaN       NaN   21482.0     NaN       NaN
경기도           NaN  722502.0       NaN  134499.0   46594.0     NaN   14932.0
경상남도          NaN  367123.0       NaN       NaN  172783.0     NaN       NaN
경상북도          NaN  298801.0       NaN   52076.0   22341.0     NaN       NaN
광주광역시         NaN  363769.0       NaN       NaN   26747.0     NaN   58340.0
대구광역시         NaN  520745.0       NaN       NaN   96531.0     NaN  100000.0
대전광역시         NaN  872312.0       NaN       NaN   19133.0     NaN       NaN
부산광역시         NaN  249939.0       NaN   49894.0   46525.0     NaN       NaN
서울특별시     54702.0  301007.0       NaN   30899.0   30132.0     NaN       NaN
세종특별자치시       NaN  117018.0       NaN       NaN   15158.0     NaN       NaN
울산광역시         NaN  309454.0       NaN       NaN   31392.0     NaN   11653.0
인천광역시         NaN  547309.0       NaN   72896.0   37537.0     NaN       NaN
전라남도          NaN  322911.0       NaN   66059.0   11529.0     NaN       NaN
전라북도          NaN  244835.0       NaN   28055.0   35100.0     NaN       NaN
제주특별자치도       NaN  318076.0       NaN       NaN   15046.0  3196.0       NaN
충청남도          NaN  312936.0       NaN       NaN   19300.0     NaN       NaN
충청북도     268625.0  629434.0  170997.0  121538.0   21217.0     NaN       NaN



도서관유형      학교도서관
시도명
강원도          NaN
경기도          NaN
경상남도         NaN
경상북도         NaN
광주광역시        NaN
대구광역시        NaN
대전광역시        NaN
부산광역시        NaN
서울특별시    28525.0
세종특별자치시      NaN
울산광역시        NaN
인천광역시        NaN
전라남도         NaN
전라북도         NaN
제주특별자치도      NaN
충청남도         NaN
충청북도     18446.0

In [140]:
df3.index = df3.index.swaplevel(0,1)
df5 = df3.unstack()
df5

          자료수(도서)                                                           \
              sum
시도명           강원도         경기도        경상남도       경상북도      광주광역시      대구광역시
도서관유형
공공도서관   2847914.0  32111062.0  11628077.0  6811687.0  4222860.0  5283846.0
대학도서관         NaN         NaN         NaN        NaN        NaN        NaN
어린이도서관        NaN   1046594.0         NaN    52076.0        NaN        NaN
작은도서관    263046.0   2336253.0   2526976.0   435117.0  1353254.0  1442401.0
장애인도서관        NaN         NaN         NaN        NaN        NaN        NaN
전문도서관         NaN     24865.0         NaN        NaN    58340.0   100000.0
학교도서관         NaN         NaN         NaN        NaN        NaN        NaN

                                                   ...                      \
                                                   ...      amax
시도명         대전광역시      부산광역시      서울특별시   세종특별자치시  ...     부산광역시     서울특별시
도서관유형                                              ...
공공도서관   5205552.0  3097306.0  9766412.0  644877.0  ...  249939.0  301007.0
대학도서관         NaN        NaN        NaN       NaN  ...       NaN       NaN
어린이도서관        NaN    61173.0    95900.0       NaN  ...   49894.0   30899.0
작은도서관    342476.0   948617.0  3134912.0   49828.0  ...   46525.0   30132.0
장애인도서관        NaN        NaN        NaN       NaN  ...       NaN       NaN
전문도서관         NaN        NaN        NaN       NaN  ...       NaN       NaN
학교도서관         NaN        NaN    54702.0       NaN  ...       NaN   28525.0

                                                                              \

시도명      세종특별자치시     울산광역시     인천광역시      전라남도      전라북도   제주특별자치도      충청남도
도서관유형
공공도서관   117018.0  309454.0  547309.0  322911.0  244835.0  318076.0  312936.0
대학도서관        NaN       NaN       NaN       NaN       NaN       NaN       NaN
어린이도서관       NaN       NaN   72896.0   66059.0   28055.0       NaN       NaN
작은도서관    15158.0   31392.0   37537.0   11529.0   35100.0   15046.0   19300.0
장애인도서관       NaN       NaN       NaN       NaN       NaN    3196.0       NaN
전문도서관        NaN   11653.0       NaN       NaN       NaN       NaN       NaN
학교도서관        NaN       NaN       NaN       NaN       NaN       NaN       NaN



시도명         충청북도
도서관유형
공공도서관   629434.0
대학도서관   170997.0
어린이도서관  121538.0
작은도서관    21217.0
장애인도서관       NaN
전문도서관        NaN
학교도서관    18446.0

[7 rows x 34 columns]

In [141]:
df3.unstack(level=0)

            자료수(도서)                                                    \
                sum
도서관유형         공공도서관     대학도서관     어린이도서관      작은도서관  장애인도서관     전문도서관
시도명
강원도       2847914.0       NaN        NaN   263046.0     NaN       NaN
경기도      32111062.0       NaN  1046594.0  2336253.0     NaN   24865.0
경상남도     11628077.0       NaN        NaN  2526976.0     NaN       NaN
경상북도      6811687.0       NaN    52076.0   435117.0     NaN       NaN
광주광역시     4222860.0       NaN        NaN  1353254.0     NaN   58340.0
대구광역시     5283846.0       NaN        NaN  1442401.0     NaN  100000.0
대전광역시     5205552.0       NaN        NaN   342476.0     NaN       NaN
부산광역시     3097306.0       NaN    61173.0   948617.0     NaN       NaN
서울특별시     9766412.0       NaN    95900.0  3134912.0     NaN       NaN
세종특별자치시    644877.0       NaN        NaN    49828.0     NaN       NaN
울산광역시     2838209.0       NaN        NaN   785272.0     NaN   11653.0
인천광역시     5152771.0       NaN   309056.0   803099.0     NaN       NaN
전라남도      6458255.0       NaN   118406.0   239427.0     NaN       NaN
전라북도      4731982.0       NaN    28055.0   912160.0     NaN       NaN
제주특별자치도   2693342.0       NaN        NaN    91242.0  3196.0       NaN
충청남도      4232171.0       NaN        NaN   270719.0     NaN       NaN
충청북도      7378160.0  170997.0   230661.0    45477.0     NaN       NaN

                                                                             \
                       amax
도서관유형       학교도서관     공공도서관     대학도서관    어린이도서관     작은도서관  장애인도서관     전문도서관
시도명
강원도           NaN  354607.0       NaN       NaN   21482.0     NaN       NaN
경기도           NaN  722502.0       NaN  134499.0   46594.0     NaN   14932.0
경상남도          NaN  367123.0       NaN       NaN  172783.0     NaN       NaN
경상북도          NaN  298801.0       NaN   52076.0   22341.0     NaN       NaN
광주광역시         NaN  363769.0       NaN       NaN   26747.0     NaN   58340.0
대구광역시         NaN  520745.0       NaN       NaN   96531.0     NaN  100000.0
대전광역시         NaN  872312.0       NaN       NaN   19133.0     NaN       NaN
부산광역시         NaN  249939.0       NaN   49894.0   46525.0     NaN       NaN
서울특별시     54702.0  301007.0       NaN   30899.0   30132.0     NaN       NaN
세종특별자치시       NaN  117018.0       NaN       NaN   15158.0     NaN       NaN
울산광역시         NaN  309454.0       NaN       NaN   31392.0     NaN   11653.0
인천광역시         NaN  547309.0       NaN   72896.0   37537.0     NaN       NaN
전라남도          NaN  322911.0       NaN   66059.0   11529.0     NaN       NaN
전라북도          NaN  244835.0       NaN   28055.0   35100.0     NaN       NaN
제주특별자치도       NaN  318076.0       NaN       NaN   15046.0  3196.0       NaN
충청남도          NaN  312936.0       NaN       NaN   19300.0     NaN       NaN
충청북도     268625.0  629434.0  170997.0  121538.0   21217.0     NaN       NaN



도서관유형      학교도서관
시도명
강원도          NaN
경기도          NaN
경상남도         NaN
경상북도         NaN
광주광역시        NaN
대구광역시        NaN
대전광역시        NaN
부산광역시        NaN
서울특별시    28525.0
세종특별자치시      NaN
울산광역시        NaN
인천광역시        NaN
전라남도         NaN
전라북도         NaN
제주특별자치도      NaN
충청남도         NaN
충청북도     18446.0

In [142]:
df3.index = df3.index.swaplevel(0,1)
df6 = df3.reset_index()
df6

        시도명   도서관유형   자료수(도서)
                          sum    amax
0       강원도   공공도서관   2847914  354607
1       강원도   작은도서관    263046   21482
2       경기도   공공도서관  32111062  722502
3       경기도  어린이도서관   1046594  134499
4       경기도   작은도서관   2336253   46594
5       경기도   전문도서관     24865   14932
6      경상남도   공공도서관  11628077  367123
7      경상남도   작은도서관   2526976  172783
8      경상북도   공공도서관   6811687  298801
9      경상북도  어린이도서관     52076   52076
10     경상북도   작은도서관    435117   22341
11    광주광역시   공공도서관   4222860  363769
12    광주광역시   작은도서관   1353254   26747
13    광주광역시   전문도서관     58340   58340
14    대구광역시   공공도서관   5283846  520745
15    대구광역시   작은도서관   1442401   96531
16    대구광역시   전문도서관    100000  100000
17    대전광역시   공공도서관   5205552  872312
18    대전광역시   작은도서관    342476   19133
19    부산광역시   공공도서관   3097306  249939
20    부산광역시  어린이도서관     61173   49894
21    부산광역시   작은도서관    948617   46525
22    서울특별시   공공도서관   9766412  301007
23    서울특별시  어린이도서관     95900   30899
24    서울특별시   작은도서관   3134912   30132
25    서울특별시   학교도서관     54702   28525
26  세종특별자치시   공공도서관    644877  117018
27  세종특별자치시   작은도서관     49828   15158
28    울산광역시   공공도서관   2838209  309454
29    울산광역시   작은도서관    785272   31392
30    울산광역시   전문도서관     11653   11653
31    인천광역시   공공도서관   5152771  547309
32    인천광역시  어린이도서관    309056   72896
33    인천광역시   작은도서관    803099   37537
34     전라남도   공공도서관   6458255  322911
35     전라남도  어린이도서관    118406   66059
36     전라남도   작은도서관    239427   11529
37     전라북도   공공도서관   4731982  244835
38     전라북도  어린이도서관     28055   28055
39     전라북도   작은도서관    912160   35100
40  제주특별자치도   공공도서관   2693342  318076
41  제주특별자치도   작은도서관     91242   15046
42  제주특별자치도  장애인도서관      3196    3196
43     충청남도   공공도서관   4232171  312936
44     충청남도   작은도서관    270719   19300
45     충청북도   공공도서관   7378160  629434
46     충청북도   대학도서관    170997  170997
47     충청북도  어린이도서관    230661  121538
48     충청북도   작은도서관     45477   21217
49     충청북도   학교도서관    268625   18446

In [144]:
# df6.set_index('시도명')
df6.set_index(['시도명', '도서관유형'])

                 자료수(도서)
                     sum    amax
시도명     도서관유형
강원도     공공도서관    2847914  354607
        작은도서관     263046   21482
경기도     공공도서관   32111062  722502
        어린이도서관   1046594  134499
        작은도서관    2336253   46594
        전문도서관      24865   14932
경상남도    공공도서관   11628077  367123
        작은도서관    2526976  172783
경상북도    공공도서관    6811687  298801
        어린이도서관     52076   52076
        작은도서관     435117   22341
광주광역시   공공도서관    4222860  363769
        작은도서관    1353254   26747
        전문도서관      58340   58340
대구광역시   공공도서관    5283846  520745
        작은도서관    1442401   96531
        전문도서관     100000  100000
대전광역시   공공도서관    5205552  872312
        작은도서관     342476   19133
부산광역시   공공도서관    3097306  249939
        어린이도서관     61173   49894
        작은도서관     948617   46525
서울특별시   공공도서관    9766412  301007
        어린이도서관     95900   30899
        작은도서관    3134912   30132
        학교도서관      54702   28525
세종특별자치시 공공도서관     644877  117018
        작은도서관      49828   15158
울산광역시   공공도서관    2838209  309454
        작은도서관     785272   31392
        전문도서관      11653   11653
인천광역시   공공도서관    5152771  547309
        어린이도서관    309056   72896
        작은도서관     803099   37537
전라남도    공공도서관    6458255  322911
        어린이도서관    118406   66059
        작은도서관     239427   11529
전라북도    공공도서관    4731982  244835
        어린이도서관     28055   28055
        작은도서관     912160   35100
제주특별자치도 공공도서관    2693342  318076
        작은도서관      91242   15046
        장애인도서관      3196    3196
충청남도    공공도서관    4232171  312936
        작은도서관     270719   19300
충청북도    공공도서관    7378160  629434
        대학도서관     170997  170997
        어린이도서관    230661  121538
        작은도서관      45477   21217
        학교도서관     268625   18446

In [148]:
df8=df3.stack()
df8.reset_index()

     시도명   도서관유형 level_2   자료수(도서)
0    강원도   공공도서관     sum   2847914
1    강원도   공공도서관    amax    354607
2    강원도   작은도서관     sum    263046
3    강원도   작은도서관    amax     21482
4    경기도   공공도서관     sum  32111062
..   ...     ...     ...       ...
95  충청북도  어린이도서관    amax    121538
96  충청북도   작은도서관     sum     45477
97  충청북도   작은도서관    amax     21217
98  충청북도   학교도서관     sum    268625
99  충청북도   학교도서관    amax     18446

[100 rows x 4 columns]